require("weicheng.plugins-setup")
require("weicheng.core.options")
require("weicheng.core.keymaps")
require("weicheng.core.colorscheme")

-- weicheng/plugins
-- some of plugins have hierachy
require("weicheng.plugins.comment")
require("weicheng.plugins.nvim-tree")
require("weicheng.plugins.lualine")
require("weicheng.plugins.telescope")
require("weicheng.plugins.nvim-cmp")
require("weicheng.plugins.lsp.mason")
require("weicheng.plugins.lsp.lspsaga")
require("weicheng.plugins.lsp.lspconfig")
-- require("weicheng.plugins.lsp.typescript-tools")
-- require("weicheng.plugins.lsp.null-ls")
require("weicheng.plugins.formatting")
require("weicheng.plugins.linting")
require("weicheng.plugins.autopairs")
require("weicheng.plugins.treesitter")
require("weicheng.plugins.gitsigns")
require("weicheng.plugins.todo")
require("weicheng.plugins.trouble")
require("weicheng.plugins.git")
require("weicheng.plugins.tailwindcss-colors")
require("weicheng.plugins.colorizer")
require("weicheng.plugins.indent-line")
